// Expo config plugin: sign Android release builds with the Goalify upload key.
//
// android/ is generated by `expo prebuild` (and gitignored), so hand edits to
// android/app/build.gradle are lost on `prebuild --clean`. This plugin re-applies
// the release signing config on every prebuild instead.
//
// The keystore details come from Gradle properties, kept OUTSIDE the repo in
// ~/.gradle/gradle.properties (see docs/play-store/android-build.md):
//   GOALIFY_STORE_FILE, GOALIFY_STORE_PASSWORD, GOALIFY_KEY_ALIAS, GOALIFY_KEY_PASSWORD
// Without them, release builds fall back to the debug key and Gradle prints a
// warning (Play Console rejects debug-signed uploads).

const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// goalify-release-signing';

const RELEASE_SIGNING_CONFIG = `
        release { ${MARKER}
            if (project.hasProperty('GOALIFY_STORE_FILE')) {
                storeFile file(GOALIFY_STORE_FILE)
                storePassword GOALIFY_STORE_PASSWORD
                keyAlias GOALIFY_KEY_ALIAS
                keyPassword GOALIFY_KEY_PASSWORD
            } else {
                println "WARNING: GOALIFY_STORE_FILE is not set in ~/.gradle/gradle.properties; release builds are signed with the DEBUG key."
            }
        }`;

const RELEASE_SIGNING_LINE =
  "signingConfig project.hasProperty('GOALIFY_STORE_FILE') ? signingConfigs.release : signingConfigs.debug";

// Debug signing config block inside signingConfigs { ... }.
const DEBUG_SIGNING_BLOCK = /(signingConfigs \{\s*debug \{[^}]*\})/;
// The `signingConfig signingConfigs.debug` line inside buildTypes.release.
const RELEASE_BUILD_TYPE_SIGNING = /(buildTypes \{[\s\S]*?release \{[\s\S]*?)signingConfig signingConfigs\.debug/;

function applyReleaseSigning(contents) {
  if (contents.includes(MARKER)) return contents;
  if (!DEBUG_SIGNING_BLOCK.test(contents) || !RELEASE_BUILD_TYPE_SIGNING.test(contents)) {
    throw new Error(
      'withAndroidReleaseSigning: android/app/build.gradle no longer matches the expected Expo template; ' +
      'update plugins/withAndroidReleaseSigning.js so release builds are not signed with the debug key.',
    );
  }
  return contents
    .replace(DEBUG_SIGNING_BLOCK, `$1${RELEASE_SIGNING_CONFIG}`)
    .replace(RELEASE_BUILD_TYPE_SIGNING, `$1${RELEASE_SIGNING_LINE}`);
}

function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, cfg => {
    cfg.modResults.contents = applyReleaseSigning(cfg.modResults.contents);
    return cfg;
  });
}

module.exports = withAndroidReleaseSigning;
module.exports.applyReleaseSigning = applyReleaseSigning;
