import { applyReleaseSigning } from '../plugins/withAndroidReleaseSigning';

// Shape of the signing/buildTypes part of android/app/build.gradle as
// generated by `expo prebuild` (Expo SDK 54 template).
const TEMPLATE = `android {
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableMinifyInReleaseBuilds
        }
    }
}
`;

describe('applyReleaseSigning', () => {
  const out = applyReleaseSigning(TEMPLATE);

  it('adds a release signing config read from gradle properties', () => {
    expect(out).toMatch(/signingConfigs \{[\s\S]*release \{[\s\S]*storeFile file\(GOALIFY_STORE_FILE\)/);
    for (const prop of ['GOALIFY_STORE_PASSWORD', 'GOALIFY_KEY_ALIAS', 'GOALIFY_KEY_PASSWORD']) {
      expect(out).toContain(prop);
    }
  });

  it('signs release builds with it when the properties exist', () => {
    const release = out.slice(out.indexOf('buildTypes'));
    expect(release).toContain("hasProperty('GOALIFY_STORE_FILE') ? signingConfigs.release : signingConfigs.debug");
  });

  it('leaves debug builds on the debug key', () => {
    const debugType = out.slice(out.indexOf('buildTypes'), out.indexOf('release {', out.indexOf('buildTypes')));
    expect(debugType).toContain('signingConfig signingConfigs.debug');
  });

  it('is idempotent (prebuild without --clean runs it again)', () => {
    expect(applyReleaseSigning(out)).toBe(out);
  });

  it('fails loudly if the template no longer matches', () => {
    expect(() => applyReleaseSigning('android { }')).toThrow(/withAndroidReleaseSigning/);
  });
});
